name: 🐛 Bug Report
description: Report a bug to help us improve the turbo-forge template.
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Please ensure you are on the latest version of the package.
  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which part of the monorepo is this related to?
      options:
        - "other"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: ... is broken. Likely cause ...
      render: markdown
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Reproduction Link and/or Steps to Reproduce
      description: |
        Please provide a link to a repository or a minimal reproduction steps. 
        Issues without reproductions are likely to be closed.
      placeholder: |
        1. Clone repo...
        2. Run command...
        3. Observe error...
        Related repo - https://github.com/user/turbo-forge-repro/commit/{commit-hash}
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Info
      description: |
        Run `pnpm debug:info` in your repository root and paste the output below.
      placeholder: |
        Node: v20.x.x
        OS: macOS/Linux/Windows
        pnpm: 9.x.x
        ...
      render: shell
    validations:
      required: true

  - type: textarea
    id: expected-actual
    attributes:
      label: Expected vs. Actual Behavior
      description: What did you expect to happen, and what happened instead?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant terminal output or error logs.
      render: shell
